---
name: CI

on:
  pull_request:

env:
  REGISTRY: docker.pkg.github.com
  DOCKER_USER: ${{ github.actor }}
  DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
  DOCKER_REPOSITORY: ${{ github.repository }}

jobs:
  build:
    if: "! contains(github.event.commits[0].message, '[skip ci]')"
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Build image
        run: |
          docker build .
