---
name: CI

on:
  push:
    branches:
      - master

  pull_request:

env:
  REGISTRY: docker.pkg.github.com
  DOCKER_USER: ${{ github.actor }}
  DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
  DOCKER_REPOSITORY: sast-scanner

jobs:
  build:
    if: "! contains(github.event.commits[0].message, '[skip ci]')"
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      
      - name: Bump Version
        run: |
          pip install semversioner==0.6.16
          ./ci-scripts/bump-version.sh

      - name: Log into registry
        run: echo "${DOCKER_PASSWORD}" | docker login "${REGISTRY}" -u $DOCKER_USER --password-stdin

      - name: Push image
        run: |
          ./ci-scripts/docker-release.sh "${REGISTRY}/${DOCKER_REPOSITORY}"
          ./ci-scripts/git-push.sh
