---
name: CI

on:
  push:
    branches:
      - master

  pull_request:

env:
  REGISTRY: docker.pkg.github.com
  DOCKER_USER: ${{ github.actor }}
  DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
  DOCKER_REPOSITORY: $${{ github.repository }}

jobs:
  build:
    if: "! contains(github.event.commits[0].message, '[skip ci]')"
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Bump Version
        run: |
          pip3 install semversioner==0.6.16
          ln -s $(which python3) $(which python)
          ./ci-scripts/bump-version.sh

      - name: Log into registry
        run: echo "$DOCKER_PASSWORD" | docker login "$REGISTORY" -u $DOCKER_USER --password-stdin

      - name: Push image
        run: |
          ./ci-scripts/docker-release.sh "$REGISTORY/$DOCKER_REPOSITORY"
          ./ci-scripts/git-push.sh
